[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = false                  # Enable or disable the solc optimizer
verbosity = 2                      # The verbosity of tests
gas_reports = ["SelfRepayingETHHarness"]
fs_permissions = [
    { access = "read", path = "./deployments/external.json" },
    { access = "read", path = "./broadcast/" }
]
rpc_endpoints = { mainnet = "${RPC_MAINNET}" }

[profile.production]
optimizer = true
optimizer_runs = 1_000_000
via_ir = true

[fuzz]
runs = 1000
