[profile.default]
optimizer = false                  # Enable or disable the solc optimizer
verbosity = 3                      # The verbosity of tests
gas_reports = ["SelfRepayingETHHarness"]
fs_permissions = [
    { access = "read", path = "./deployments/" },
    { access = "read", path = "./broadcast/" }
]
rpc_endpoints = { mainnet = "${RPC_MAINNET}" }

[profile.production]
via_ir = true

[fuzz]
runs = 1000
